import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../components/Header";
import { NavBar } from "../components/NavBar";
import { Cards } from "../components/Cards";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <NavBar />
      </div>
      <div className={styles.imageContainer}>
        <div>
          <h2>All Pats</h2>
        </div>
      </div>
      <h1>Pets for your choose</h1>
      <section className={styles.sectionDog}>
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
        <Cards />
      </section>
    </div>
  );
};

export default Home;
